### ISSUE TITLE
Recipe conflict with Applied Energistics 2

### ISSUE THREAD

**Issue by Technici4n** [Chainmail-Studios/Astromine#350] opened 2020-11-08 08:56 UTC
![image](https://user-images.githubusercontent.com/13494793/98460895-7ff64380-21a8-11eb-892a-83a840e5dde4.png)

Smelting quartz dust into regular quartz conflicts with AE2's recipe for silicon. I suggest you move that recipe to the compressor instead, like I have with Modern Industrialization.

**Comment by vini2003** [comment] 2020-11-20 22:35
Duplicate of #215, but that's a good idea - will do.

**Closed as completed by vini2003** 2020-11-20 22:35 UTC
