### ISSUE TITLE
[1.16.4] Crash when pressing CTRL or ALT with latest Fabric API

### ISSUE THREAD

**Issue by HockeyZman2000** [Chainmail-Studios/Astromine#378] opened 2020-12-31 04:58 UTC
Upon loading up the game with Astromine: Complete 1.11.4 and Fabric API 0.29.0, pressing either the CTRL or ALT key on the keyboard while in the menus (not in a singleplayer or multiplayer world) results in a crash. Also occurs for Fabric API version 0.28.4. This could be happening for other keys as well, but I have not done extensive testing.

Crashlog: https://pastebin.pl/view/c42a173e

**Comment by shedaniel** [comment] 2020-12-31 05:15
duplicate of #369

**Closed as completed by shedaniel** 2020-12-31 05:15 UTC
