### ISSUE TITLE
Unregistered stuff - Blame report.

### ISSUE THREAD

**Issue by K0-RR** [Chainmail-Studios/Astromine#386] opened 2021-01-30 23:16 UTC
****************** Blame Report 1.16.4-2.4.1 ******************

 This is an experimental report. It is suppose to automatically read
 the JSON of all the unregistered ConfiguredFeatures, ConfiguredStructures,
 and ConfiguredCarvers. Then does its best to collect the terms that seem to
 state whose mod the unregistered stuff belongs to.

Possible mods responsible for unregistered stuff:

astromine:crude_oil
astromine:meteor

**Comment by shedaniel** [comment] 2021-03-01 04:42
Duplicate of #329

**Closed as completed by shedaniel** 2021-03-01 04:42 UTC
Labels: duplicate
