### ISSUE TITLE
UI Buttons Bug

### ISSUE THREAD

**Issue by ecumber** [Chainmail-Studios/Astromine#306] opened 2020-09-28 19:43 UTC
The machine UI has a very strange bug. The buttons that control electricity I/O can still be clicked even when you're in a different tab.
Video here: https://streamable.com/33kznn

**Comment by vini2003** [comment] 2020-09-28 20:15
Duplicate of https://github.com/Mixinors/Astromine/issues/297.

**Closed as completed by vini2003** 2020-09-28 20:15 UTC
