### ISSUE TITLE
[Minor Gameplay Annoyance] Adding items to input slots or removing them from output slots resets machine progress

### ISSUE THREAD

**Issue by Desempregago** [Chainmail-Studios/Astromine#298] opened 2020-09-21 19:07 UTC
the title explains itself.

**Comment by Desempregago** [comment] 2020-09-21 19:14
![aaa](https://user-images.githubusercontent.com/14002834/93810774-8135d600-fc25-11ea-915c-2d1b077d3e45.gif)

**Comment by shedaniel** [comment] 2020-09-21 19:21
Duplicate of #291

**Closed as completed** 2020-09-21 19:21 UTC
Labels: bug, duplicate
