### ISSUE TITLE
SoundEvent registry synchronization failure

### ISSUE THREAD

**Issue by Darka139** [Chainmail-Studios/Astromine#283] opened 2020-09-16 21:26 UTC
after leaving the aof3 server and trying to reconnect i get the following error.  Has happened multiple times to multiple players.

```
[17:19:24] [main/INFO]: Connecting to aof3.lab717.com, 25565
[17:19:25] [Netty Client IO #1/ERROR]: Feature: Not a JSON object: "allure:speleothem"
[17:19:25] [Netty Client IO #1/ERROR]: Feature: Not a JSON object: "techreborn:ore_techreborn_tungsten_ore"; Not a JSON object: "techreborn:ore_techreborn_sodalite_ore"; Not a JSON object: "techreborn:ore_techreborn_sheldonite_ore"; Not a JSON object: "techreborn:ore_techreborn_peridot_ore"
[17:19:25] [main/INFO]: [STDOUT]: New minimap session initialized!
[17:19:25] [main/INFO]: [STDOUT]: New world map session initialized!
[17:19:25] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[17:19:25] [CraftPresence/ERROR]: Asset Name "overworld" does not exist, attempting to use an alternative Icon "aof3-logo_512x512"...
[17:19:25] [CraftPresence/INFO]: To Add Support for this Icon, Please Request for this Icon to be Added to the Default Client ID or Add the Icon under the following Name: "overworld".
[17:19:25] [CraftPresence/INFO]: Fallback Icon for "overworld" Found! Using Fallback Icon with Name "aof3-logo_512x512"!
[17:19:25] [CraftPresence/ERROR]: Asset Name "_" does not exist, attempting to use an alternative Icon "aof3-logo_512x512"...
[17:19:25] [CraftPresence/INFO]: To Add Support for this Icon, Please Request for this Icon to be Added to the Default Client ID or Add the Icon under the following Name: "_".
[17:19:25] [CraftPresence/INFO]: Fallback Icon for "_" Found! Using Fallback Icon with Name "aof3-logo_512x512"!
[17:19:27] [main/INFO]: [STDOUT]: connected to  
[17:19:27] [main/INFO]: [STDOUT]: setting state on   to 0
[17:19:27] [main/ERROR]: Registry remapping failed!
net.fabricmc.fabric.impl.registry.sync.RemapException: Received ID map for minecraft:sound_event contains IDs unknown to the receiver!
 - astromine:block.machine.click
 - astromine:block.incinerator.incinerate
	at net.minecraft.class_2370.remap(class_2370.java:703) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.apply(RegistrySyncManager.java:281) ~[9ce1ed46-1382-4cc9-9925-6f5ea2f41c0d.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.lambda$receivePacket$0(RegistrySyncManager.java:88) ~[9ce1ed46-1382-4cc9-9925-6f5ea2f41c0d.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) [?:1.8.0_265]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) [intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) [intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:103) [intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:990) [intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:656) [intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-minecraft-1.16.2-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.9.3+build.207.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.9.3+build.207.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.9.3+build.207.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[17:19:27] [main/INFO]: Using trinkets in DurabilityViewer
[17:19:27] [main/INFO]: [STDOUT]: Minimap session finalized.
[17:19:27] [main/INFO]: [STDOUT]: World map session finalized.
[17:19:27] [Thread-278/INFO]: [STDOUT]: World map force-cleaned!
[17:19:30] [main/WARN]: Sending packet net.minecraft.class_2817@2631e1e1 to server failed, not connected!
[17:19:31] [main/WARN]: Sending packet net.minecraft.class_2817@5687fda7 to server failed, not connected!
```

**Comment by vini2003** [comment] 2020-09-16 21:27
what the ungodly fu

**Comment by Monster-Zer0** [comment] 2020-09-16 21:41
yeah, now it's happening more often. https://imgur.com/HBg91Gf is what the players see.


a reboot seems to fix temporarily.

**Comment by TheEssem** [comment] 2020-09-16 21:53
I got this error after updating my server when I realized that it was because I hadn't updated the client as well. Make sure both the server and client are using the same mod versions.

**Comment by Monster-Zer0** [comment] 2020-09-16 21:59
yeah, that's ruled out. everyone is using the correct client.

NOTE

players can login.. but after some time if they try to come back.. they get this error... using the same exact minecraft client/version/etc

**Comment by Monster-Zer0** [comment] 2020-09-16 23:17
I have a heap dump when the issue is occuring.. but it's like 2.6 GB so not sure if you can use it or not.

**Comment by shedaniel** [comment] 2020-09-24 03:28
Is this still happening?

**Comment by vini2003** [comment] 2020-10-12 23:42
Will be closing as we haven't received any more reports of this, and Astromine appears to be working in servers.

**Comment by Shnupbups** [comment] 2020-11-09 06:33
Got another report on the discord, but I think I've found the source of the issue

**Closed as completed** 2020-11-09 06:34 UTC
Labels: bug
