### ISSUE TITLE
Possible Conflict with Unknown Modpack?

### ISSUE THREAD

**Issue by michaelslec** [Chainmail-Studios/Astromine#379] opened 2020-12-31 06:00 UTC
Hello,

I'm building a custom modpack with some buddies, and AstroMine causes the game to crash on the main menu if you press any non-alphanumeric keys (alt, ctrl, win).

I know that removing Astromine removes the problem; however, I can't make sense of the stack trace. I think it's leading to some dependent of one of the mods I have installed.

Let me know what other information I can provide!

Here is the log:

```
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2020-12-30 21:57:35 PST
Description: Unexpected error

java.lang.IllegalStateException: Cannot send packet to server while not in game!
    at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.7)
    at net.fabricmc.fabric.impl.networking.ClientSidePacketRegistryImpl.sendToServer(ClientSidePacketRegistryImpl.java:51)
    at net.fabricmc.fabric.api.network.ClientSidePacketRegistry.sendToServer(ClientSidePacketRegistry.java:70)
    at net.fabricmc.fabric.api.network.ClientSidePacketRegistry.sendToServer(ClientSidePacketRegistry.java:89)
    at grondag.fermion.modkeys.impl.ModKeysHandler.sendUpdatePacket(ModKeysHandler.java:91)
    at grondag.fermion.modkeys.impl.ModKeysHandler.update(ModKeysHandler.java:83)
    at net.fabricmc.fabric.api.event.client.ClientTickCallback.lambda$null$0(ClientTickCallback.java:39)
    at net.fabricmc.fabric.impl.event.lifecycle.client.LegacyClientEventInvokers.lambda$onInitializeClient$0(LegacyClientEventInvokers.java:29)
    at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$null$2(ClientTickEvents.java:65)
    at net.minecraft.client.MinecraftClient.handler$cdm000$onEndTick(MinecraftClient:11886)
    at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1612)
    at net.minecraft.client.MinecraftClient.render(MinecraftClient:1021)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:681)
    at net.minecraft.client.MinecraftClient.handler$bol000$afterCrashHandled(MinecraftClient:10404)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:704)
    at net.minecraft.client.main.Main.main(Main:215)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.16.4
  Minecraft Version ID: 1.16.4
  Operating System: Linux (amd64) version 5.9.14-arch1-1
  Java Version: 1.8.0_271, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 2602166320 bytes (2481 MB) / 3724541952 bytes (3552 MB) up to 8589934592 bytes (8192 MB)
  CPUs: 4
  JVM Flags: 11 total; -XX:-OmitStackTraceInFastThrow -Xms512M -Xmx8192M -XX:MetaspaceSize=256M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xss1M
  Suspected Mods: Fabric Events Lifecycle (v0) (fabric-events-lifecycle-v0), Fabric Networking (v0) (fabric-networking-v0), Fabric Loader (fabricloader), Fabric Lifecycle Events (v1) (fabric-lifecycle-events-v1), Fermion Modifier Keys (fermion-modkeys)
  Fabric Mods: adorn: Adorn 1.12.2+1.16.4
               advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
               amecsapi: Amecs API 1.1.1+mc1.16-rc1
               angerable-patch: Angerable Patch 1.0.0-1.16.1
               architectury: Architectury 1.2.64
               artifacts: Artifacts 2.0.2+1.16.4-fabric
               artifice: Artifice 0.13.1+1.16.2-rc1
               astromine: Astromine 1.11.4+fabric-1.16.3
               astromine-core: Astromine: Core 1.11.4+fabric-1.16.3
               astromine-discoveries: Astromine: Discoveries 1.11.4+fabric-1.16.3
               astromine-foundations: Astromine: Foundations 1.11.4+fabric-1.16.3
               astromine-technologies: Astromine: Technologies 1.11.4+fabric-1.16.3
               astromine-transportations: Astromine: Transportations 1.11.4+fabric-1.16.3
               autoconfig1u: Auto Config v1 Updated 3.3.1
               battletowers: Battle Towers 3.3.1-beta-1.16.4
               betterdroppeditems: Better Dropped Items 1.2.4-1.16.2
               betterend: Better End 0.8.3-beta
               betternether: Better Nether 5.0.4
               betterthanmending: BetterThanMending 1.2.0
               blade: Blade 2.0.0
               blockus: Blockus 2.0.1+1.16.4
               blue_endless_jankson: jankson 1.2.0
               bowinfinityfix: Bow Infinity Fix rv9
               campanion: Campanion 1.3.1+build.51
               cardinal-components: Cardinal Components API 2.6.0
               cardinal-components-base: Cardinal Components API (base) 2.7.9
               cardinal-components-block: Cardinal Components API (blocks) 2.6.0
               cardinal-components-chunk: Cardinal Components API (chunks) 2.6.0
               cardinal-components-entity: Cardinal Components API (entities) 2.7.9
               cardinal-components-item: Cardinal Components API (items) 2.7.9
               cardinal-components-level: Cardinal Components API (world saves) 2.6.0
               cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.6.0
               cardinal-components-util: Cardinal Components API (utilities) 2.6.0
               cardinal-components-world: Cardinal Components API (worlds) 2.6.0
               chainmail: Chainmail 0.5.0
               cinderscapes: Cinderscapes 1.3.0+build.51
               cloth-armor-api-v1: Cloth Armor API v1 1.4.8
               cloth-basic-math: Cloth Basic Math 0.5.1
               cloth-client-events-v0: Cloth Client Events v0 1.4.9
               cloth-common-events-v1: Cloth Common Events v1 1.4.8
               cloth-config2: Cloth Config v4 4.8.3
               cloth-datagen-api-v1: Cloth Datagen v1 1.4.8
               cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.8
               cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.8
               cloth-utils-v1: Cloth Utils v1 1.4.5
               computercraft: CC:T for Fabric 1.91.2
               croptopia: Croptopia 1.0.6-1.16.4-FABRIC
               darkness: True Darkness 1.6.58
               expandedstorage: ExpandedStorage 5.6.31
               extraalchemy: Extra Alchemy 1.3.1
               fabric: Fabric API 0.28.4+1.16
               fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
               fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
               fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
               fabric-commands-v0: Fabric Commands (v0) 0.2.0+6a2618f53a
               fabric-containers-v0: Fabric Containers (v0) 0.1.9+a03e98793a
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
               fabric-diagonal-panes: Fabric Diagonal Panes 0.4.0
               fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
               fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
               fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+6a2618f53a
               fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c595
               fabric-language-kotlin: Fabric Language Kotlin 1.4.21+build.1
               fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
               fabric-models-v0: Fabric Models (v0) 0.1.1+6a2618f53a
               fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+a03e98793a
               fabric-networking-v0: Fabric Networking (v0) 0.3.1+2a4333d33a
               fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
               fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.3+be155ae23a
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+6a2618f53a
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+6a2618f53a
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+6a2618f53a
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+6a2618f53a
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+6a2618f53a
               fabric-rendering-v1: Fabric Rendering (v1) 1.4.0+6a2618f53a
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.0+552549d53a
               fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
               fabric-structure-api-v1: Fabric Structure API (v1) 1.1.1+f1d8af063a
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
               fabric-textures-v0: Fabric Textures (v0) 1.0.5+6a2618f53a
               fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
               fabricloader: Fabric Loader 0.10.8
               falling_tree: FallingTree 2.8.1
               fermion: Fermion 2.1.191
               fermion-modkeys: Fermion Modifier Keys 1.8.180-snapshot
               fiber: fiber 0.23.0-2
               glassential: Glassential 1.16.4-1.1.5
               jankson: Jankson 3.0.1+j1.2.0
               javax_vecmath_vecmath: vecmath 1.5.2
               kirin: Kirin UI 1.7-1.16.2
               kubejs: KubeJS 1.5.4
               lambdabettergrass: LambdaBetterGrass 1.0.1+1.16.3
               lambdynlights: LambDynamicLights 1.3.2+1.16.4
               libblockattributes: LibBlockAttributes 0.8.4
               libblockattributes_core: LibBlockAttributes (Core) 0.8.4
               libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.4
               libblockattributes_items: LibBlockAttributes (Items) 0.8.4
               libcd: LibCapableData 3.0.3+1.16.3
               libgui: LibGui 3.1.0+1.16.3
               libstructure: LibStructure 1.5
               lithium: Lithium 0.6.0
               lithium-api: Lithium API 0.6.0
               loadcatcher: Entrypoint Catcher 2.0.0
               magna: Magna 1.4.3-1.16.2
               maybe-data: Maybe data 1.0.0-1.16.2
               minecraft: Minecraft 1.16.4
               mm: Manningham Mills 2.1
               mo_glass: Mo Glass 1.5-MC1.16.4
               modern_industrialization: Modern Industrialization 0.3.9
               modmenu: Mod Menu 1.14.13+build.19
               moenchantments: Mo'Enchantments 1.13.8
               mostructures: Mo' Structures 1.0.1+mc.1.16.4
               mousewheelie: Mouse Wheelie 1.6.1+mc1.16.4
               multi_item_lin: Multi Item Lin 1.0.0
               namepain: Name Pain 1.3.1
               netherite_plus: Netherite Plus Mod 1.2.0
               notenoughcrashes: Not Enough Crashes 2.1.4+1.16.4
               org_codehaus_groovy_groovy: groovy 3.0.3
               org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
               org_jetbrains_annotations: annotations 20.0.0
               org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.21
               org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.21
               org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.21
               org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.21
               org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
               org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
               org_joml_joml: joml 1.9.25
               oro_config: OroArmor Config -0df99c92b1-1
               patchouli: Patchouli 1.16.4-48-FABRIC
               phosphor: Phosphor 0.7.0+build.10
               piglib: Piglib 1.0.1
               presencefootsteps: Presence Footsteps r29+1.16.4
               reach-entity-attributes: Reach Entity Attribute 1.0.1
               reborncore: Reborn Core 4.6.2+build.108
               roughlyenoughitems: Roughly Enough Items 5.8.10
               roughlyenoughitems-api: REI (API) 5.8.10
               roughlyenoughitems-default-plugin: REI (Default Plugin) 5.8.10
               roughlyenoughitems-runtime: REI (Runtime) 5.8.10
               shapes: Shapes 2.0.0+build.10
               slight-gui-modifications: 'Slight' GUI Modifications 1.6.1
               sodium: Sodium 0.1.0
               spruceui: SpruceUI 1.6.4
               staffofbuilding: Staff of Building 1.2.4-1.16.2
               static-content: Static Content 1.0.1-1.16.2
               staticdata: Static Data 1.1.2
               step-height-entity-attribute: Step Height Entity Attribute 1.0.0
               structure-helpers: Structure Helpers 3.0.0
               team_reborn_energy: Energy 0.1.1
               techreborn: Tech Reborn 3.7.2+build.189
               terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.0+build.1
               terraform-config-api-v1: Terraform Config API (v1) 1.0.0+build.1
               terraform-dirt-api-v1: Terraform Dirt API (v1) 1.0.0+build.1
               terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.0+build.1
               terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.0+build.1
               terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.0+build.1
               terraform-tree-api-v1: Terraform Tree API (v1) 1.0.1+build.2
               terraform-wood-api-v1: Terraform Wood API (v1) 1.0.0+build.1
               terrestria: Terrestria 2.1.5+build.28
               trade: Trade 1.1.2
               trinkets: Trinkets 2.6.7
               tweed: Tweed API 3.0.0-beta.22
               waila: Hwyla 1.9.22
               wrenchable: Wrenchable 1.0.0+1.16.1
               xaerominimap: Xaero's Minimap 20.29.1
               xaeroworldmap: Xaero's World Map 1.11.4
               xpstorage: XP Storage 1.3+1.16.4
  Patchouli open book context: n/a
  Launched Version: 1.16.4
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: AMD HAWAII (DRM 2.50.0, 5.9.14-arch1-1, LLVM 11.0.0) GL version 4.5 (Compatibility Profile) Mesa 20.3.1, AMD
  GL Caps: Using framebuffer using OpenGL 3.0
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fabric'
  Type: Client (map_client.txt)
  Graphics mode: fancy
  Resource Packs: Fabric Mods
  Current Language: English (US)
  CPU: 4x Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
  Client Crashes Since Restart: 2
  Integrated Server Crashes Since Restart: 0

```

**Comment by shedaniel** [comment] 2020-12-31 06:07
duplicate of #369

**Closed as completed by shedaniel** 2020-12-31 06:07 UTC

**Comment by michaelslec** [comment] 2021-01-01 00:53
Thank you!
