### ISSUE TITLE
Update to the latest Fermion - Astromine Complete crash with FAPI 0.28.0

### ISSUE THREAD

**Issue by K0-RR** [Chainmail-Studios/Astromine#369] opened 2020-12-11 01:03 UTC
1.16.4, was fine with Fabric API 0.27.1.
Astromine Complete crashes the game when trying to type the name of the new world in Menu. I'm not entirely sure if typing causes a crash but for sure clicking CTRL+A to select the "New World" text does.

crash report - https://hatebin.com/brasgfjlsa

**Comment by Noaaan** [comment] 2020-12-11 21:15
Just experienced the same issue. Is indeed related to pressing buttons on the create world screen. Created a similar crash by holding RSHIFT at the menu. Does seem to be an issue with Fermion though, not Astromine. That or it is their implementation of it.

**Comment by CodedWithInsulin** [comment] 2020-12-11 21:29
exact same error AS long is i don press LShift or Rshift it generates the world but wont go pass 100% screen
issue with astromine!

(turning off the astromine mods till futrue updates its sush a fun mod !!)

**Comment by Noaaan** [comment] 2020-12-11 21:32
Just looked into this and it is because of Fermion. Astromine uses this library, hence why it crashes.
If you manage to avoid clicking any modifier keys you will be able to generate a world, and in-game it works. I have notified the developer (Grondag) of this issue, and he said it would be an easy fix.

**Comment by Noaaan** [comment] 2020-12-14 20:15
This has been fixed in the newest version of Fermion. If you install it besides Astromine it will take priority, and prevent this crash.
https://www.curseforge.com/minecraft/mc-mods/fermion/files/3136837
Close the issue once confirmed 😄

**Comment by K0-RR** [comment] 2020-12-15 10:43
Inside Astromine.jar, when you navigate to /META-INF/jars/astromine-core-*.jar/META-INF/jars/ there are many dependencies but I don't see Fermion. Can somebody tell me where it is?

**Comment by Noaaan** [comment] 2020-12-15 10:55
Ive tried looking, but it ISNT as far as i know. There is a single use case in the transportation module.

**Closed as completed** 2021-01-16 08:08 UTC
