### ISSUE TITLE
astromine crash  when ever a player opens a chest

### ISSUE THREAD

**Issue by skitzozombie25** [Chainmail-Studios/Astromine#202] opened 2020-08-09 17:55 UTC
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 8/9/20 6:49 PM
Description: Exception in server tick loop

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_2281.method_9534(class_2281.java:207)
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:893)
	at net.minecraft.class_3225.method_14262(class_3225.java:328)
	at net.minecraft.class_3244.method_12046(class_3244.java:976)
	at net.minecraft.class_2885.method_12547(class_2885.java:36)
	at net.minecraft.class_2885.method_11054(class_2885.java:10)
	at net.minecraft.class_2600.method_11072(class_2600.java:21)
	at net.minecraft.class_2600$$Lambda$8572/1301808640.run(Unknown Source)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:763)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:154)
	at net.minecraft.class_1255.method_16075(class_1255.java:118)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:745)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:739)
	at net.minecraft.class_1255.method_5383(class_1255.java:103)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:723)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256)
	at net.minecraft.server.MinecraftServer$$Lambda$7852/593685148.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [astromine.mixins.json:PiglinBrainMixin] from phase [DEFAULT] in config [astromine.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:643)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:595)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
	... 28 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE_ASSIGN") on net/minecraft/class_4838::wearsGoldArmorInject with priority 1000 cannot inject into net/minecraft/class_4838::method_24719(Lnet/minecraft/class_1309;)Z merged by net.piglintag.mixin.PiglinBrainMixin with priority 1000 [PREINJECT Applicator Phase -> astromine.mixins.json:PiglinBrainMixin -> Prepare Injections ->  -> handler$cbp000$wearsGoldArmorInject(Lnet/minecraft/class_1309;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Ljava/lang/Iterable;Ljava/util/Iterator;Lnet/minecraft/class_1799;Lnet/minecraft/class_1792;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 28 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1264836608 bytes (1206 MB) / 4962910208 bytes (4733 MB) up to 11453595648 bytes (10923 MB)
	CPUs: 12
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12288m -Xms256m -XX:PermSize=256m
	Fabric Mods: 
		adabraniummod: Adabranium Mod 1.1.5.1
		adorn: Adorn 1.10.0+1.16.1
		advancements-enlarger: Advancements Enlarger 0.2.2
		adventurez: AdventureZ 1.0.7
		allure: Allure 1.2.1
		angerable-patch: Angerable Patch 1.0.0-1.16.1
		aopalliance_aopalliance: aopalliance 1.0
		appleskin: AppleSkin 1.0.11
		aquarius: Aquarius 1.0.1
		artifice: Artifice 0.8.0+1.16-rc1
		assetvalidator: Asset Validator 1.0.2
		astromine: Astromine 1.5.2
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		automated_crafting: Automated Crafting 1.1.3+1.16.1
		autoswitch: AutoSwitch 2.10.2
		autoswitch-api: AutoSwitch API 1.0.0
		bambootweaks: Bamboo Tweaks unspecified
		banner_capes: Banner Capes 0.2.1
		battletowers: Battle Towers 3.0.2-beta-1.16.1
		beachslimes: Beach Slimes 2.1.0+mc1.16.1
		bebooks: Better Enchanted Books 1.1.1
		better_wandering_trader: Better Wandering Trader 1.4.0
		bettergraves: Better Graves 0.3.0
		betternether: Better Nether 3.4.3
		betterstones: Better Stones 0.0.3
		betterthanmending: BetterThanMending 1.1.1
		blockshifter: Blockshifter 1.0.3+1.16.1
		blue_endless_jankson: jankson +
		bunch-o-trinkets: Bunch O' Trinkets 1.0.1
		byg: BYG 1.0.12
		caelus: Caelus API 0.0.5-1.16.1
		campanion: Campanion 1.1.13+build.35
		cardinal-components: Cardinal Components API 2.4.2
		cardinal-components-base: Cardinal Components API (base) 2.4.2
		cardinal-components-block: Cardinal Components API (blocks) 2.4.2
		cardinal-components-chunk: Cardinal Components API (chunks) 2.4.2
		cardinal-components-entity: Cardinal Components API (entities) 2.4.2
		cardinal-components-item: Cardinal Components API (items) 2.4.2
		cardinal-components-level: Cardinal Components API (world saves) 2.4.2
		cardinal-components-util: Cardinal Components API (utilities) 2.4.2
		cardinal-components-world: Cardinal Components API (worlds) 2.4.2
		cavebiomes: Cave Biomes 0.2.4
		cinderscapes: Cinderscapes 1.0.7+build.43-1.16.1
		clear-skies: Clear Skies 1.4.43
		cloth-api: Cloth API 1.0.8
		cloth-armor-api-v1: Cloth Armor API v1 1.0.8
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.0.8
		cloth-common-events-v1: Cloth Common Events v1 1.0.8
		cloth-config2: Cloth Config v4 4.6.0
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.0.8
		cloth-scissors-api-v1: Cloth Scissors API v1 1.0.8
		cloth-utils-v1: Cloth Utils v1 1.0.8
		coalnugget: Coal Nugget 1.2.0.4
		com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.9.0
		com_fasterxml_jackson_core_jackson-core: jackson-core 2.9.0
		com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.9.0
		com_fasterxml_jackson_dataformat_jackson-dataformat-yaml: jackson-dataformat-yaml 2.9.0
		com_fasterxml_jackson_module_jackson-module-kotlin: jackson-module-kotlin 2.9.0
		com_google_inject_guice: guice 4.2.3
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_squareup_moshi_moshi: moshi 1.9.2
		com_squareup_okio_okio: okio 1.16.0
		completeconfig: CompleteConfig 0.3.1
		connected_block_textures: Connected Block Textures 0.1.1+1.16
		cotton: Cotton 1.0.5
		cotton-cauldron: Cotton Cauldron 1.0.4
		cotton-commons: Cotton Commons 1.0.4
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-datapack: Cotton Datapack 1.0.5
		cotton-logging: Cotton Logging 1.0.0-rc.4
		cotton-player-events: Cotton Player Events 1.0.2
		craftable_utilities: Craftable Utilities 1.0.1
		craftingpad: Crafting Pad 1.16-fabric0.13.1-1.0.5
		crusade: Crudade Mod 1.1.2
		curios: Curios API 1.16.1-0.3
		dankstorage: Dank Storage 1.1d_1.16.1
		dark-loading-screen: Dark Loading Screen 1.4.2
		dataloader: Data Loader 2.1.0+mc1.16.1
		daylight_mobs: Daylight Mobs 1.0.0
		diggusmaximus: Diggus Maximus 1.3.0-1.16
		dimute: Dimension Mutability 0.1.1
		dungeonsmod: Dungeons Mod Lite 1.16.1-0.2.9.3
		durabilityviewer: Giselbaers Durability Viewer 1.16-fabric0.13.1-1.7.3
		dynamicfps: Dynamic FPS 1.1.4
		dynamicsoundfilters: Dynamic Sound Filters 1.1.2+1.16.1
		earthtojavamobs: Earth2Java 1.1.0+1.16.1
		easierenchanting: Easier Enchanting 1.2.0
		ecotones: Ecotones 0.5.1
		eldritch_mobs: Eldritch Mobs 1.2.9
		elytra-recipe: Elytra Recipe 1.0.0
		enderitemod: Enderite Mod 1.1.3
		enderlift: Enderlift 1.0.5
		endreborn: End: Rebellion 1.6
		equip: EquipZ 1.6.2
		essentials-base: Essentials 0.2.7+1.16.1
		extraalchemy: Extra Alchemy 1.1.0
		extraorigins: Extra Origins 12
		ezpas: Ezpas 1.1.1-1.16.1
		fabric: Fabric API 0.17.0+build.386-1.16.1
		fabric-api-base: Fabric API Base 0.1.3+12a8474c7c
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-diagonal-panes: Fabric Diagonal Panes 0.3.0
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f02
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-furnaces: Fabric Furnaces 1.3.1-1.16.1
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.0+fe81e12502
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+f404f3be02
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c502
		fabric-language-kotlin: Fabric Language Kotlin 1.3.72+build.1
		fabric-language-scala: Fabric Language Scala 0.3.2.12
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+e83e061c02
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+386eb69e02
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.7+2242e77202
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+a2d21ddd02
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.4+34d6c87102
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.1.0+be551d3c02
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+97324d1102
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.1+91fca5cd02
		fabricloader: Fabric Loader 0.9.1+build.205
		fairenchanting: FairEnchanting 1.2.0
		fatxporbs: Fat Experience Orbs 0.0.7
		fermion: Fermion 2.3.196
		fermion-gui: Fermion GUI 2.3.196
		fermion-modkeys: Fermion Modifier Keys 1.8.180-snapshot
		fermion-orientation: Fermion Orientation 1.0.180-snapshot
		fermion-simulator: Fermion Simulator 1.6.196
		fermion-varia: Fermion Varia 2.1.196
		fiber: fiber 0.23.0-1
		firstperson: FirstpersonModel 1.2.1
		flesh2leather: Flesh2Leather 1.0.0
		ftc: Fabric Title Changer 1.0.4
		gbfabrictools: GBfabrictools 1.2.2+1.16
		givemehats: Give Me Hats! 1.2.8
		godown: Go Down 0.2.0+1.16.1
		golem: GolemZ 1.3.1
		golemsgalore: Golems Galore 0.1.4+mc.1.16.1
		greater_eye: Greater Eye of Ender 1.0.21
		grindenchantments: Grind Enchantments 1.1.1+1.16.1
		haema: Haema 1.2.1
		hardcorequesting: Hardcore Questing Mode 0.2.1-SNAPSHOT
		harvest: Harvest 1.2.12
		hotm: Heart of the Machine 1.16.1-0.1.3
		hotpocket: HotPocket 0.0.1
		howlingwolves: Howling Wolves 1.0.0+build.1
		indrev: Industrial Revolution 1.4.9-BETA
		inmis: Inmis 1.2.0-1.16.1
		intotheomega: Into the Omega 1.0.0-beta-1.16.1
		inventorysorter: Inventory Sorter 1.7.0-1.16
		invo: FriendZ 1.5.4
		jankson: Jankson 3.0.0+j1.2.0
		javax_inject_javax_inject: javax.inject 1
		jumploader: Jumploader 2.0.0
		jumpoverfences: JumpOverFences 1.16-0.0.3
		kibe: Kibe 1.1.12-BETA
		kyrptconfig: Kytpt Config 1.1.0-1.16
		ladderwarp: LadderWarp 1.1.0+1.16.x
		lakeside: Lakeside 1.0.2+1.16.1
		lambdynlights: LambDynamicLights 1.2.2+1.16.1
		leaf-decay: Leaf Decay 1.2.0-1.16.1
		libblockattributes: LibBlockAttributes 0.7.0
		libblockattributes_core: LibBlockAttributes (Core) 0.7.1-pre.4
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.7.1-pre.4
		libblockattributes_items: LibBlockAttributes (Items) 0.7.1-pre.4
		libcd: LibCapableData 2.5.0+1.16.1
		libgamerule: LibGamerule ${version}
		libgui: LibGui 2.3.0+1.16.1
		library_of_exile: Library of Exile 1.0.1
		libstructure: Libstructure 1.3
		lithium: Lithium 0.5.1
		magna: Magna 1.3.2-1.16.1
		materialisation: Materialisation 3.0.2
		minecraft: Minecraft 1.16.1
		mm: Manningham Mills 2.0
		mmorpg: Age of Exile 1.0.7
		mo_glass: Mo Glass 1.3-MC1.16.1
		mobz: MobZ 2.4.3
		modid: XEnchant 1.0.7.2
		modmenu: Mod Menu 1.14.5+build.30
		moenchantments: Mo'Enchantments 1.12.4-beta2
		more_gems: More Gems 1.0.48
		moreberries: More Berries 1.3.1
		moreores: More ores 1.1.0
		morepaths: More Paths 0.0.2
		moretotems: More Totems 2.5
		mostructures: Mo' Structures 1.0.0-pre2+mc.1.16
		mysql_mysql-connector-java: mysql-connector-java 5.1.46
		nomadbooks: Nomad Books 0.5.4
		onsoulfire: On Soul Fire r4
		org_aeonbits_owner_owner: owner 1.0.10
		org_codehaus_groovy_groovy: groovy 3.0.3
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
		org_jetbrains_annotations: annotations 19.0.0
		org_jetbrains_exposed_exposed-core: exposed-core 0.23.1
		org_jetbrains_exposed_exposed-java-time: exposed-java-time 0.23.1
		org_jetbrains_exposed_exposed-jdbc: exposed-jdbc 0.23.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.72
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.7
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.7
		org_postgresql_postgresql: postgresql 42.2.2
		org_slf4j_slf4j-api: slf4j-api 1.8.0-beta1
		org_xerial_sqlite-jdbc: sqlite-jdbc 3.28.0
		org_yaml_snakeyaml: snakeyaml 1.26
		origins: Origins 1.16-0.3.4
		parchment: Parchment 1.0.2+1.15.2
		patchouli: Patchouli 1.16-39-FABRIC
		pethernortalflux: PetherNortalFlux unspecified
		phosphor: Phosphor 0.6.0+build.7
		piglintag: PiglinTag 1.0.0
		pigpoop: Pig Poop 1.1.3
		plantinajar: Plant In A Jar 1.6.1+1.16.1
		playerabilitylib: Pal 1.2.0
		polydungeons: PolyDungeons 1.0.3
		polymorph: Polymorph 0.0.3-1.16.1
		qcommon-croco: Croco 2.1.3
		rare-ice: Rare Ice 0.2.1
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		reborncore: Reborn Core 4.3.4+build.64
		recipe_improver: Recipe Improver 1.1.0
		reliccraft: RelicCraft 1.0.29+1.16.1
		repurposed_structures: Repurposed Structures 1.4.1
		ring_of_attraction: Ring Of Attraction 1.0.21
		ring_of_enderchest: Ring of Enderchest 1.0.21
		ring_of_growth: Ring Of Growth 1.0.19
		ring_of_miner: Ring Of Miner 1.0.16
		ringsofascension: Rings of Ascension 1.0.6
		roughlyenoughitems: Roughly Enough Items 4.11.0
		satin: Satin 1.4.0
		shapes: Shapes 2.0.0+build.10
		sign_editor: Better Signs & Frames mc-1.16.1-0.6.1
		silky_spawners: Silky Spawners 2.0.0+build.1-1.16
		simpleteleporters: Simple Teleporters 2.2.0
		simplexterrain: Simplex Terrain 0.6.5
		sizeentityattributes: Size Entity Attributes r2
		slabhelper: Slab Helper 1.3.2
		sleepvote: SleepVote ${version}
		slight-gui-modifications: 'Slight' GUI Modifications 1.2.0
		slotlink: slotlink 1.0.3+minecraft-1.16.1
		sodium: Sodium 0.1.0
		soulbound: Soulbound 1.0.1
		special-circumstances: Special Circumstances 1.6.196
		spinnery: Spinnery 3.0.59
		spruceui: SpruceUI 1.5.8
		static-content: Static Content 1.0.0-1.16.1
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		structure-helpers: Structure Helpers 2.1.0
		structurized: Structurized 1.0.0
		tacocraft: TacoCraft 1.3.1+mc.1.16
		team_reborn_energy: Energy 0.1.0
		techreborn: Tech Reborn 3.4.5+build.88
		terraform: Terraform 2.1.7+build.31
		terrestria: Terrestria 2.0.4+build.50
		timber: Timber Mod 1.6
		traverse: Traverse 2.2.14+build.28
		trees-do-not-float: Trees Do Not Float 1.10.90
		trinkets: Trinkets 2.6.3
		twine: Twine 1.0.4+1.16.1
		uncraftable: Uncraftables 1.3.4-1.16.1
		universalcomponents: Universal Components 0.7.2+1.16-pre2
		vanilla-hammers: Vanilla Hammers 2.0.3-1.16.1
		vanillaenhanced: VanillaEnhanced 1.0.0-1.16.1
		vanillaexcavators: Vanilla Excavators 1.1.0
		vanillaplusbiomes: Vanilla Plus Biomes 0.2.2
		waila: Hwyla 1.9.22
		water-erosion: Water Erosion 1.1.1
		whiplash: Whiplash: Magic Dungeons 1.0.0
		winged: Winged Mod 1.16-1.2
		wolveswitharmor: Wolves With Armor 1.5.1-1.16.1
		wrenchable: Wrenchable 1.0.0+1.16.1
		xaerominimap: Xaero's Minimap 20.19.0
	Patchouli open book context: n/a
	Player Count: 1 / 8; [class_3222['skitzozombie25'/177, l='ServerLevel[test  5]', x=37.70, y=73.90, z=104.70]]
	Data Packs: vanilla (incompatible), fabric/crusade, fabric/materialisation, fabric/ezpas, fabric/hotpocket, fabric/kibe (incompatible), fabric/betternether, fabric/adventurez, fabric/astromine, fabric/mo_glass, fabric/polydungeons, fabric/moretotems, fabric/bunch-o-trinkets, fabric/techreborn, fabric/piglintag, fabric/repurposed_structures, fabric/morepaths, fabric/battletowers, fabric/enderitemod, fabric/structure-helpers, fabric/mostructures, fabric/curios, fabric/moreores, fabric/origins, fabric/adorn, fabric/golemsgalore, fabric/vanillaenhanced, fabric/terrestria, fabric/vanillaexcavators, fabric/mmorpg (incompatible), fabric/banner_capes, fabric/hardcorequesting, fabric/wolveswitharmor, fabric/elytra-recipe, fabric/invo, fabric/ecotones, fabric/bambootweaks, fabric/intotheomega, fabric/haema, fabric/cotton-commons, fabric/ring_of_growth, fabric/winged, fabric/harvest, fabric/twine, fabric/inmis, fabric/byg, fabric/cinderscapes, fabric/aquarius, fabric/whiplash, fabric/dungeonsmod, fabric/silky_spawners, fabric/indrev, fabric/craftingpad, fabric/eldritch_mobs, fabric/dankstorage (incompatible), fabric/lambdynlights, fabric/adabraniummod, fabric/betterstones, fabric/reliccraft, fabric/greater_eye, fabric/blockshifter, fabric/tacocraft, fabric/mobz, fabric/fabric-tool-attribute-api-v1, fabric/extraorigins, fabric/rare-ice, fabric/enderlift, fabric/ring_of_miner, fabric/endreborn, fabric/ring_of_enderchest, fabric/earthtojavamobs, fabric/extraalchemy, fabric/libcd, fabric/flesh2leather, fabric/vanilla-hammers, fabric/allure, fabric/automated_crafting, fabric/simpleteleporters, fabric/nomadbooks, fabric/plantinajar, fabric/campanion, fabric/uncraftable, fabric/traverse, fabric/more_gems, fabric/beachslimes, fabric/moreberries, fabric/slotlink, fabric/slabhelper, fabric/fabric-furnaces, fabric/craftable_utilities (incompatible), fabric/hotm, fabric/ring_of_attraction, fabric/coalnugget, fabric/golem, fabric/equip, file/cr (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by shedaniel** [comment] 2020-08-09 18:02
Duplicate of #199

**Closed as completed by shedaniel** 2020-08-09 18:02 UTC
Labels: duplicate
