### ISSUE TITLE
Crash with energonrelics-0.1.1+1.16.2.jar

### ISSUE THREAD

**Issue by ghost** [Chainmail-Studios/Astromine#209] opened 2020-08-17 16:14 UTC
MC: 1.16.2
Fabric: fabric-api-0.18.0+build.397-1.16.jar
Astromine: astromine-1.6.1+fabric-1.16.2.jar

magna-a7ee77a9.jar is included in astromine-1.6.1+fabric-1.16.2.jar, which is why I'm reporting this conflict here.
I'm reporting this at energonrelic's repo as well.

`[main/WARN]: @Redirect conflict. Skipping energonrelics.mixins.json:MixinWorld->@Redirect::breakBlock(Lnet/minecraft/class_1937;ILnet/minecraft/class_2338;I)V with priority 1000, already redirected by magna.mixins.json:WorldMixin->@Redirect::cancelSyncWorldEvent(Lnet/minecraft/class_1937;ILnet/minecraft/class_2338;I)V with priority 1000`

**Comment by TheBrokenRail** [comment] 2020-08-18 01:39
This is an issue caused by two mods doing a ``@Redirect`` on the same method to prevent block break particles from being displayed in specific situations. This would be fixed by https://github.com/FabricMC/fabric/pull/1023.

**Comment by ghost** [comment] 2020-08-18 01:43
Great!  Thank you!
I look forward to playing with energon relics when the PR gets merged.

**Comment by ghost** [comment] 2020-08-19 00:28
This is currently resolved/bypassed on energon relic's side.

**Comment by MariaTheDinkus** [comment] 2020-08-19 00:29
Thanks for the report, will close.

**Closed as completed by MariaTheDinkus** 2020-08-19 00:29 UTC
